### PR TITLE
Collections section link added to all apps indices

### PR DESCRIPTION
**Pull request by pablopareja**

### CODE REVIEW

**Review by tiagojsag — COMMENTED** [review]
I appreciate the effort and proactivity in documenting this, but I'm also concerned by the fact that this whole file was effectively not published until now. My concern is that this is intentional, due to its content being outdated or something. 

@pablopareja did you happen to use the rest of these endpoints, and can validate if the information here is accurate?
 @01painadam you were the original author (2 years ago, I know). do you know why this is hidden?

thanks

**Comment by pablopareja** [comment]
@tiagojsag I've tested all the endpoints in the production API and the docs were accurate except a couple of things that I fixed in my last commit 999ee88471ff96e4105990750a424bc54c3b52b3

So, I guess that unless there was a reason why this was hidden I think we should be good to publish it, (in fact these endpoints have been being used for a good while already)

**Comment by tiagojsag** [comment]
@ikas thoughts?

**Comment by tiagojsag** [comment]
https://www.pivotaltracker.com/story/show/170050085

**Review by ikas — APPROVED** [review]

**Comment by ikas** [comment]
> @ikas thoughts?

About why this was hidden, I have no clue. Other than that, LGTM 👍

**Pull request merged**
