### PR TITLE
RW index section sorted alphabetically

### PR DESCRIPTION
**Pull request by pablopareja**

### CODE REVIEW

**Comment by pablopareja** [comment]
@tiagojsag Should I also update the other indices?

**Review by tiagojsag — COMMENTED** [review]
Not sure I agree with this change. I'd rather aim to have the most important/core/ferequently used stuff at the top, and the least important things at the bottom. Not saying the current order cant be improved, I'm just saying that, IMO, alphabetical may not be the best way to improve. Thoughts?

**Comment by pablopareja** [comment]
I agree with the idea of having sections as part of the index; however, I do think that inside a specific section, we should have elements sorted alphabetically.
Almost every time that I want to find a specific endpoint, I have to go through the list back and forth several times until I can find where it is... 😅

**Comment by tiagojsag** [comment]
ok, so to clarify, my understanding of section is basically each of the files inside `source/includes/api`.

So inside each section, the way I try to organize id basically get, create, update, delete. There are odd sections, but those that are CRUD based are roughly organized this way. 

As for how sections are sorted, I still think my previous comment applies, and I don't think your comment is a disagreement with that, but please clarify

As for your need to quickly find something: there is a poor man's search bar at the top. Perhaps we can improve/optimize the titles to make the search more efficient and useful to you?

**Comment by pablopareja** [comment]
This is the current state of the index:
image
As it stands now, it neither is sorted alphabetically nor has the most important groups of endpoints at the top. 
What would you say are the main "groups" that we should have? We could sort the index with the most important ones at the top and then alphabetically inside of them.
What do you think? @tiagojsag

**Comment by tiagojsag** [comment]
```
  - api/authentication
  - api/dataset
  - api/query
  - api/fields
  - api/widget
  - api/layer
  - api/metadata
  
  - api/vocabulary
  - api/collections
  
  - api/geostore
  - api/subscriptions
  
  - api/topic
  - api/dashboard
  
  - api/favourites
  - api/graph
  
  - api/areas
  - api/jiminy
  - api/tasks
  - api/contact
  - api/user_management
  - api/microservices
  - api/troubleshooting
  - errors
  - attribution
```

this is roughly my suggestion of sorting these. Ignore the empty lines

This is, ofc, open for debate.

As for your suggestion of

> then alphabetically inside of them

If I understand it correctly as being sorting the subsections inside each section alphabetically, I currently don't see a reason to go alphabetically, especially since we don't have a standard naming scheme for subsections. Even if we did, most APIs use CRUD or RCUD sorting, never alphabetically, for the same reason discussed before - alphabetically adds very little value to the human user, especially when compared with other, more pragmatic approaches.

Thoughts?

**Comment by tiagojsag** [comment]
Since this has been idle for so long, I'm closing it

**Pull request closed without merging**
