### PR TITLE
Geometry analysis tutorial

### PR DESCRIPTION
**Pull request by loganbyers**
Create a new tutorial for geometry analysis, which covers working with
vector tiles, the query endpoint, and shows a practical example of how
datasets are likely to be created, transformed, and linked together
across different providers to make a more ready-to-use system.

The text in the tutorial has been completed to a first-draft level - it is ready for review.

### CODE REVIEW

**Review by ethanroday — COMMENTED** [review]
This is great! No real substantial comments from me. Will take a closer look at the code later today to see if I have any suggestions.

**Comment by loganbyers** [comment]
Great - glad to hear it. I just added the code examples in case you want to look over complete versions and not piece it together yourself.

**Review by logoul — COMMENTED** [review]
Hi Logan, I see that you are hardcoding datasetIdForTCL, datasetIdForWDPAGeometries and queryDatasetId. 
I am realizing now that these dataset ids can become deprecated, if we create a new versions. As a matter of fact queryDatasetId will definitely become deprecated after every quarterly data update, where we will create new dataset tables in elastic search with all recalculated zonal statistics. 
This is definitely one of the biggest deficiencies of the current WRI Api architecture. 
Not quite sure what to do about it now until we implement something that can always point to the latest version. 
In the meantime, should we explicitly tell users in the tutorial to acquire latest ids through a support email before using them in the queries?

**Comment by loganbyers** [comment]
Yes this seems like it could be setting up a maintenance requirement going forward. The tutorial content wouldn't be very hard to update with new IDs assuming the schema of the data aren't changing frequently.

Another option, which might be overstepping on complexity, is to put these IDs and any other fields that will vary over time into their own Dataset and register it with the API, hosting and updating the CSV within this GitHub repo.

So make a table like:

```
key | value
datasetIdForTCL | .....
datasetIdForWDPAGeometries | .....
vectorLayerForWDPA | ....
datasetIdForQueryTable | .....
```

Register this with the API, then in the tutorial point to this _config dataset_ as the way to get all necessary ~dynamic values...

```javascript
var datasetIdForTCL = (await fetch("api.resourcewatch.org/v1/query/?sql=SELECT value FROM <table> WHERE key='datasetIdForTCL'")).data[0];
```

The tutorial could still keep all the examples of what the API responses look like, but those may become out of sync over time. Hopefully without major consequences.

**Comment by logoul** [comment]
I actually think that this idea of creating an endpoint with the latest IDs is a good idea.
Ethan, what do you think?

**Comment by ethanroday** [comment]
Definitely a clever workaround, @loganbyers 😄 
@logoul depending on the priority with which you think this needs to go out, I see a couple of options:
1. Implement this workaround with the new dataset.
2. Leave this unreleased and do a quick prototype of the "uber-dataset" concept, then revise to use the uber-dataset ids rather than the dataset ids.
3. Release as-is and revise once uber-dataset work is done.
I guess in theory my preference would be for #2, but in practice probably #1. The negative to #1 is that is still requires maintenance, because it's effectively acting as an uber-dataset won't be automatically updated when new versions are released.

**Comment by logoul** [comment]
@ethanroday, actually if we are committed to implementing 'uber-dataset', then I agree  that we should just go in that direction and not spend time on workarounds. In the meantime, I'll add a task in our quarterly maintenance JIRAs to update developer docs. We have to update other places in the API to point to new ids anyway.

**Pull request merged**
