### PR TITLE
[WIP] Split docs pages into parts

### PR DESCRIPTION
**Pull request by ethanroday**
**NOTE: Definitely _do not_ try to look through the changes. Since so many links changed, it's just a big mess. Just check out and build locally.**

Todo:

- [x] Fix links
- [x] Move Errors section to common behaviors (and fix the error code messages)
- [ ] Think of better names for "common behaviors", "common concepts", and "core resources" (I am very open to suggestions!)

Started out as an attempt to fix the performance issues we've been seeing because `index-rw.html` was too big. Ended up adding some content and restructuring some pages to make things make a little more sense. Summary of changes:

- Moved concept documentation to its own `concepts.html`
- Split concept docs into three sections: common behaviors (caching, sorting/filtering, pagination), common API concepts (applications, user roles, etc.), core resources (dataset, etc.); also split concepts for the first two categories into their own files
- Moved reference documentation to its own `reference.html`
- Created a new quickstart guide at `quickstart.html` and moved account/token creation there
- Created a new "front page" at `index.html` that gives some brief intro and links to quickstart, concepts, reference, and tutorials

Some smaller changes as well:
- Changed `index-gfw.html`, `index-aqueduct.html`, and `index-rw.html` to just redirect to `index.html`. If anyone complains about logos I'll take care of it 😛 
- Replaced ui.resourcewatch.org link in the bottom left with link to the quickstart guide
- Added a link to developer docs in the bottom left (front page only)
- Removed microservices from the main references doc (kept a link) so they're only in the developer docs
- Fixed some examples that were missing the `shell` annotation
- Also addressed [GTC-949](https://gfw.atlassian.net/browse/GTC-949)
- Reversed page titles for easier readability (e.g. 'Resource Watch API Reference -> Reference - Resource Watch API)

### CODE REVIEW

**Comment by tiagojsag** [comment]
Overall I think the structure makes sense, but I think it creates a browsing/navigation problem. Ultimately, I felt lost at times, and it was hard to go to certain places depending on where I was. Maybe an example will help:

You reach the home, and you quickly learn about "concepts", "reference" and "tutorial" sections. You click on one of those sections, and are taken to a new page. However, that new page is now the "root" page. In "concepts", there's no clear high-level mention to "reference" or "tutorials" or the actual docs homepage itself. And because all the pages look alike, it's easy to not notice that there's more to read than what's on the sidebar of any of the sections.

Another example/use case that may illustrate this is going to the "dataset concept", learning about what a dataset is and does, and then wanting to learn more about the endpoints themselves. There's no quick way to make that jump. And sure, we could add manual links at the end, but I think that's not an optimal solution.

I think the underlying problem is that slate is meant to be a single page, which is why it has that sidebar menu rendered in browser-land, and we're trying to use it to build a multi-page site. So I see a few potential solutions:
- we can try to find and fix the performance issue that ultimately lead to this refactor
- we could try to see if it's possible to add some sort of high-level, always present menu, that would allow easy navigation across the different sections
- (a lot more complex) we could replace slate with something else

**Review by ikas — COMMENTED** [review]
I definitely think this is an improvement on what we currently have in terms of performance :+1: most pages now load immediately, except for `reference.html` (which ofc still has lots of content, but it's loading in ~5 seconds, which is great)

I do see Tiago's point about navigation, and I felt the same - to me, I frame the main issue as _there is no way of navigating back to the new "front page" from concepts, tutorials, or reference_. We can go back via the browser's back button, but visually we have no clue of the implicit hierarchy we are enforcing. 

Maybe we can explore some potential solutions as Tiago said - IMO, having a set of links in the left sidebar that are always visible (in all pages) that allow you to navigate between the different "home pages" we now have would be a good solution.

In any case, I think the current state is already a significant improvement performance-wise, so great job :+1:

**Comment by ethanroday** [comment]
@ikas funny that you say that because I did add a link at the top of every page that takes you back home, but I guess that is just not prominent enough.

I will try the following:
1. Update Slate to see if that solves the performance issue
2. Look into adding a persistent sidebar that takes you between the four main pages

**Comment by ethanroday** [comment]
🎉 Tada!

image

It's hardcoded in `layout.erb` for now, which is not optimal.

**Comment by ethanroday** [comment]
Enabled 4 levels of nesting based on the instructions [here](https://github.com/slatedocs/slate/wiki/Deeper-Nesting)

image

**Review by ikas — APPROVED** [review]
Looks really neat, thanks for doing this @ethanroday :rocket:

**Pull request merged**
